=== pzw0612/TechEdu/xsd/cache_key.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://com.yhd.shareservice/autoclear/cachekey" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://com.yhd.shareservice/autoclear/cachekey" 
    elementFormDefault="unqualified">
   <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
  
	<xsd:element name="cacheKeys">
			<xsd:complexType>
				   <xsd:sequence>
				       <xsd:element ref="cacheKey" minOccurs="0" maxOccurs="unbounded"/>
				   </xsd:sequence>
	              <xsd:attributeGroup ref="rootAttributes"></xsd:attributeGroup>
			</xsd:complexType>
	</xsd:element>

	<xsd:attributeGroup name="rootAttributes">
		<xsd:attribute name="namespace" type="xsd:string" use="optional"></xsd:attribute>
	    <xsd:attribute name="version" type="xsd:string"  use="required"></xsd:attribute>
   </xsd:attributeGroup>
   

	<xsd:element name="cacheKey">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:group ref="cacheKeyElements"/>
					<xsd:attributeGroup ref="cacheKeyAttributes"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="identifiedType" abstract="true">
		<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
	</xsd:complexType>

	<xsd:group name="cacheKeyElements">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="argument"/>
				<xsd:element ref="values" minOccurs="0"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:group>

	<xsd:attributeGroup name="cacheKeyAttributes">
         <xsd:attribute name="prefix" type="xsd:string" use="optional"></xsd:attribute>
	    <xsd:attribute name="isUsePrefixVersion" type="isUseType" use="optional"></xsd:attribute>
   </xsd:attributeGroup>
   
	<xsd:element name="argument">
	    <xsd:complexType>
	        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	        <xsd:attribute name="table" type="xsd:string" use="required"></xsd:attribute>
	        <xsd:attribute name="column" type="xsd:string" use="required"></xsd:attribute>
	        <xsd:attribute name="isUseValueVersion" type="isUseType" use="optional"></xsd:attribute>
	        <xsd:attribute name="isUseNameVersion" type="isUseType" use="optional"></xsd:attribute>
	    </xsd:complexType>
	</xsd:element>
	
	<xsd:simpleType name="isUseType">
		  <xsd:restriction base="xsd:string">
			    <xsd:enumeration value="true"/>
			    <xsd:enumeration value="false"/>
			    <xsd:enumeration value=""/>
		  </xsd:restriction>
   </xsd:simpleType>

	<xsd:element name="values" >
	    <xsd:complexType>
	        <xsd:sequence>
	           <xsd:element ref="value" maxOccurs="unbounded"></xsd:element>
	        </xsd:sequence>
	    </xsd:complexType>
	</xsd:element>
	
	<xsd:element name="value">
	    <xsd:complexType>
	        <xsd:attribute name="table" type="xsd:string" use="required"></xsd:attribute>
	        <xsd:attribute name="column" type="xsd:string" use="required"></xsd:attribute>
	    </xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pzw0612/TechEdu/src/main/resources/autoclear/cache_key_case.xml
<?xml version="1.0" encoding="UTF-8"?>
<cacheKeys xmlns="http://com.yhd.shareservice/autoclear/cachekey"  
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
        xsi:schemaLocation="http://com.yhd.shareservice/autoclear/cachekey 
             http://com.yhd.shareservice/autoclear/cachekey/cache_key.xsd"  
        version="1.0" namespace="pss"> 
     
     <!-- 有values, 有版本升级字段 ,参数filed1 为 name 版本类型-->
     <!-- pss_aa0_filed1_v1_%1%_filed2_%2% -->
     <cacheKey id="aa0" >
          <argument name="filed1" column="FIELD1" table="TEST" isUseNameVersion="true" />
          <argument name="filed2" column="FIELD2" table="TEST"  />
          <values>
              <value column="filed1" table="TEST"/>
              <value column="filed2" table="TEST"/>
              <value column="filed3" table="TEST"/>
              <value column="filed4" table="TEST"/>
          </values>
     </cacheKey>
     
     <!-- 有values, 无版本升级字段 -->
     <!-- pss_queryFieldxx_filed1_%1%_filed2_%2% -->
     <cacheKey id="aa" prefix="queryFieldxx">
          <argument name="filed1" column="FIELD1" table="TEST" />
          <argument name="filed2" column="FIELD2" table="TEST"  />
          <values>
              <value column="filed1" table="TEST"/>
              <value column="filed2" table="TEST"/>
              <value column="filed3" table="TEST"/>
              <value column="filed4" table="TEST"/>
          </values>
     </cacheKey>
     
     <!-- 有values, 有版本升级字段 ,参数filed1 为 name 版本类型-->
     <!-- pss_queryFieldxx_filed1_v1_%1%_filed2_%2% -->
     <cacheKey id="aa1" prefix="queryFieldxx">
          <argument name="filed1" column="FIELD1" table="TEST" isUseNameVersion="true" />
          <argument name="filed2" column="FIELD2" table="TEST"  />
          <values>
              <value column="filed1" table="TEST"/>
              <value column="filed2" table="TEST"/>
              <value column="filed3" table="TEST"/>
              <value column="filed4" table="TEST"/>
          </values>
     </cacheKey>
     
     <!-- 无values -->
     <!-- pss_queryFieldxx_filed1_%1% -->
     <cacheKey id="aa2" prefix="queryFieldxx">
          <argument name="filed1" column="FIELD1" table="TEST"/>
     </cacheKey>
     
     <!-- 无values ，有版本升级字段 ，参数filed1 为 value 版本类型-->
     <!-- pss_queryFieldxx_filed1_%1%_v1 -->
     <cacheKey id="aa3" prefix="queryFieldxx">
          <argument name="filed1" column="FIELD1" table="TEST" isUseValueVersion="true"/>
     </cacheKey>
     
     <!-- 无values ，有版本升级字段 ，参数filed1 为 name 版本类型-->
     <!-- pss_queryFieldxx_filed1_v1_%1% -->
     <cacheKey id="aa4" prefix="queryFieldxx">
          <argument name="filed1" column="FIELD1" table="TEST" isUseNameVersion="true"/>
     </cacheKey>
     
     <!-- 无values ，有版本升级字段 ，参数filed 为 name 版本类型,无前缀prex-->
     <!-- pss_aa5_filed1_%1% -->
     <cacheKey id="aa5" >
          <argument name="filed1" column="FIELD1" table="TEST" isUseNameVersion="true"/>
     </cacheKey>
    
     <cacheKey id="aa6" >
          <argument name="filed1" column="FIELD1" table="TEST" isUseNameVersion="true"/>
          <values>
              <value column="" table=""/>
              <value column="" table=""/>
              <value column="" table=""/>
              <value column="" table=""/>
          </values>
     </cacheKey>
</cacheKeys>

=== pzw0612/TechEdu/src/main/resources/autoclear/merchant_cache_key.xml
<?xml version="1.0" encoding="UTF-8"?>
<cacheKeys xmlns="http://com.yhd.shareservice/autoclear/cachekey"  
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
        xsi:schemaLocation="http://com.yhd.shareservice/autoclear/cachekey 
             http://com.yhd.shareservice/autoclear/cachekey/cache_key.xsd"  
        version="1.0">  
    <!-- 例子 pss_queryBaseMerchantById_id_%1% -->
	<cacheKey id="queryBaseMerchantById">
		<argument name="id" table="merchant" column="id"/>
		<values>
		    <value table="Merchant" column="ID"/>
			<value table="Merchant" column="IS_YIHAODIAN"/>
			<value table="Merchant" column="MERCHANT_COMPANY_NAME"/>
			<value table="Merchant" column="MERCHANT_NAME"/>
			<value table="Merchant" column="MERCHANT_CODE"/>
			<value table="Merchant" column="IS_TRANSFER_INCOME"/>
			<value table="Merchant" column="SBY_TYPE"/>
			<value table="Merchant" column="FETCH_PROVINCE_ID"/>
			<value table="Merchant" column="FETCH_CITY_ID"/>
			<value table="Merchant" column="FETCH_COUNTY_ID"/>
			<value table="Merchant" column="FETCH_DETAIL_ADDRESS"/>
			<value table="Merchant" column="MERCHANT_ADD"/>
			<value table="Merchant" column="LINKMAN_NAME"/>
			<value table="Merchant" column="LINKMAN_TEL"/>
			<value table="Merchant" column="SUPPORT_SALE_TYPE"/>
			<value table="Merchant" column="STORE_TYPE_ID"/>
			<value table="Merchant" column="SUPPLIER_ID"/>
			<value table="Merchant" column="INVOICE_TYPE"/>
			<value table="Merchant" column="IS_SUPPORT_CONTRACT"/>
			<value table="Merchant" column="IS_DELETE"/>
			<value table="Merchant" column="MERCHANT_STATUS"/>
			<value table="Merchant" column="LINKMAN_EMAIL"/>
			<value table="Merchant" column="CREAT_TIME"/>
			<value table="Merchant" column="VALIDATE_TIME"/>
		</values>
	</cacheKey>
	
	<!-- 示例 pss_queryProvinceIdByMerchantId_id_%2% -->
	<cacheKey id="queryProvinceIdByMerchantId">
		<argument name="id" table="MERCHANT_AREA" column="MERCHANT_ID"/>
		<values>
		    <value table="MERCHANT_AREA" column="PROVINCE_ID"/>
		</values>
	</cacheKey>
	
	<cacheKey id="queryMerchantIdAndProvinceIdByMerchantIds">
		<argument name="id" table="MERCHANT_AREA" column="MERCHANT_ID"/>
		<values>
		    <value table="MERCHANT_AREA" column="PROVINCE_ID"/>
		    <value table="MERCHANT_AREA" column="MERCHANT_ID"/>
		</values>
	</cacheKey>
	
	<cacheKey id="querySimpleMerchantAndMerchantAreaByMerchantIds">
		<argument name="id" table="merchant" column="id"/>
	</cacheKey>
	<cacheKey id="queryProvinceIdAndMerchantIdAndIsYihaodianByMerchantIds">
		<argument name="id" table="merchant" column="id"/>
	</cacheKey>
	<cacheKey id="queryMerchantCodAreaByBaseCondition">
		<argument name="merchantId" table="merchant_cod_area" column="merchant_id"/>
		<argument name="countyId" table="merchant_cod_area" column="county_id"/>
	</cacheKey>
	
</cacheKeys>
