=== pzw0612/TechEdu/xsd/keys_pair.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://com.yhd.shareservice/autoclear/keyspair" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://com.yhd.shareservice/autoclear/keyspair" 
    elementFormDefault="unqualified">
   <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
   
	<xsd:element name="writeKeysPairs">
			<xsd:complexType>
				   <xsd:sequence>
				       <xsd:element ref="writeKeysPair" minOccurs="1" maxOccurs="unbounded"/>
				   </xsd:sequence>
			</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="writeKeysPair">
		<xsd:complexType>
			<xsd:sequence>
	              <xsd:element ref="className"></xsd:element>
	              <xsd:element ref="methodName" ></xsd:element>
	              <xsd:element  ref="associatedKeys" minOccurs="1" maxOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="associatedKeys">
                <xsd:complexType>
                     <xsd:sequence>
                           <xsd:element ref="associatedKey" minOccurs="1" maxOccurs="unbounded"></xsd:element>
                     </xsd:sequence>
                </xsd:complexType>
	</xsd:element>
	
	 <xsd:element name="associatedKey">
	     <xsd:complexType>
	          <xsd:complexContent>
	               <xsd:extension base="identifiedType">
	                     <xsd:group ref="associatedKeyElements" minOccurs="0" maxOccurs="1"></xsd:group>
	                     <xsd:attributeGroup ref="associatedKeyAttr"></xsd:attributeGroup>
	               </xsd:extension>
	          </xsd:complexContent>
	     </xsd:complexType>
	 </xsd:element>
	<xsd:complexType name="identifiedType">
		<xsd:attribute name="keyId" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:attributeGroup name="associatedKeyAttr">
           <!-- 以逗号分隔的参数 -->
           <xsd:attribute name="affectedArgument" type="xsd:string" use="optional"></xsd:attribute>
           <xsd:attribute name="clearCacheStrategy" type="clearCacheStrategyType" ></xsd:attribute>
	</xsd:attributeGroup>
	
	<!-- 缓存清理策略 -->
	 <xsd:simpleType name="clearCacheStrategyType">
	     <xsd:restriction base="xsd:string">
	         <xsd:enumeration value="directlyRemove"></xsd:enumeration>
	         <xsd:enumeration value="updateKeyVersion"></xsd:enumeration>
	     </xsd:restriction>
	 </xsd:simpleType>
 
 	<xsd:group name="associatedKeyElements">
		<xsd:sequence>
            <xsd:element ref="argumentRetrieval"></xsd:element>
		</xsd:sequence>
	</xsd:group>

	<xsd:element name="className">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="methodName">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="argumentRetrieval">
	    <xsd:complexType>
              <xsd:choice minOccurs="1" maxOccurs="2">
	               <xsd:element ref="sqlMapClient" minOccurs="1" maxOccurs="1"></xsd:element>
	               <xsd:element ref="iBATISId" minOccurs="1" maxOccurs="1"></xsd:element>
              </xsd:choice>
	        <xsd:attribute name="type" type="typeEnum" default="input"></xsd:attribute>
	    </xsd:complexType>
	</xsd:element>
	
	 <xsd:simpleType name="typeEnum">
	     <xsd:restriction base="xsd:string">
	         <xsd:enumeration value="input"></xsd:enumeration>
	         <!-- sqlMapClient,iBATISId -->
	         <xsd:enumeration value="sql"></xsd:enumeration>
	         <!-- sqlMapClient -->
	         <xsd:enumeration value="code"></xsd:enumeration>
	     </xsd:restriction>
	 </xsd:simpleType>
	 
	<xsd:element name="sqlMapClient">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="iBATISId">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="1" maxOccurs="1"/>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== pzw0612/TechEdu/src/main/resources/autoclear/wirte_pair_case.xml
<?xml version="1.0" encoding="UTF-8"?>
<writeKeysPairs xmlns="http://com.yhd.shareservice/autoclear/keyspair"  
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://com.yhd.shareservice/autoclear/keyspair 
        http://com.yhd.shareservice/autoclear/keyspair/keys_pair.xsd"> 
        
   <!-- 使用直接清理缓存策略 -->
   <writeKeysPair>
       <className>aa</className>
       <methodName>bb</methodName>
       <associatedKeys>
         <associatedKey keyId="cc" clearCacheStrategy="directlyRemove"/>
       </associatedKeys>
   </writeKeysPair>
   
   <!-- 使用升级版本缓存策略 -->
   <writeKeysPair>
       <className>aa1</className>
       <methodName>bb1</methodName>
       <associatedKeys>
         <associatedKey keyId="cc" clearCacheStrategy="updateKeyVersion"/>
       </associatedKeys>
   </writeKeysPair>

   <!-- 使用直接清理、升级版本缓存策略 -->
   <writeKeysPair>
       <className>aa2</className>
       <methodName>bb2</methodName>
       <associatedKeys>
         <associatedKey keyId="cc" clearCacheStrategy="updateKeyVersion"/>
         <associatedKey keyId="cc2" clearCacheStrategy="directlyRemove"/>
       </associatedKeys>
   </writeKeysPair>
   
   <!-- 使用直接清理、升级版本缓存策略, 检索方式为 sql -->
   <writeKeysPair>
       <className>aa3</className>
       <methodName>bb3</methodName>
       <associatedKeys>
			<associatedKey keyId="cc" affectedArgument="aa1,aa2,aa3" clearCacheStrategy="directlyRemove">
			    <argumentRetrieval type="sql">
			        <sqlMapClient>pssClient</sqlMapClient>
			        <iBATISId>sqlStatementId</iBATISId>
			    </argumentRetrieval>
			</associatedKey>
			<associatedKey keyId="cc2" />
       </associatedKeys>
   </writeKeysPair>
   
   <!-- 使用直接清理、升级版本缓存策略, 检索方式为 code -->
   <writeKeysPair>
       <className>aa4</className>
       <methodName>bb4</methodName>
       <associatedKeys>
			<associatedKey keyId="cc" affectedArgument="aa1,aa2,aa3" clearCacheStrategy="directlyRemove">
			    <argumentRetrieval type="code">
			        <sqlMapClient>pssClient</sqlMapClient>
			    </argumentRetrieval>
			</associatedKey>
			<associatedKey keyId="cc2" />
       </associatedKeys>
   </writeKeysPair>
   
</writeKeysPairs>

=== pzw0612/TechEdu/target/classes/autoclear/modifyMerchantRemoteService.xml
<?xml version="1.0" encoding="UTF-8"?>
<writeKeysPairs xmlns="http://com.yhd.shareservice/autoclear/keyspair"  
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://com.yhd.shareservice/autoclear/keyspair 
        http://com.yhd.shareservice/autoclear/keyspair/keys_pair.xsd"> 
   <writeKeysPair>
       <className>com.yhd.pss.merchant.remote.ModifyMerchantServiceRemoteImpl</className>
       <methodName>updateMerchant</methodName>
       <associatedKeys>
         <associatedKey keyId="queryBaseMerchantById" clearCacheStrategy="directlyRemove"/>
       </associatedKeys>
   </writeKeysPair>
   <writeKeysPair>
       <className>com.yhd.pss.merchant.remote.ModifyMerchantServiceRemoteImpl</className>
       <methodName>deleteMerchantAreaByMerchantId</methodName>
       <associatedKeys>
			<associatedKey keyId="queryProvinceIdByMerchantId"/>
			<associatedKey keyId="queryMerchantIdAndProvinceIdByMerchantIds" />
       </associatedKeys>
   </writeKeysPair>
   
   <writeKeysPair>
       <className>com.yhd.pss.merchant.remote.ModifyMerchantServiceRemoteImpl</className>
       <methodName>insertMerchantArea</methodName>
       <associatedKeys>
			<associatedKey keyId="queryProvinceIdByMerchantId"/>
			<associatedKey keyId="queryMerchantIdAndProvinceIdByMerchantIds"/>
       </associatedKeys>
   </writeKeysPair>
   
</writeKeysPairs>
